version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    network_mode: host
    ports:
      - "8080"
    volumes:
      - /dev:/dev
      - ../:/workspace:cached
    environment:
      - DISPLAY
    command: /bin/sh -c "while sleep 1000; do :; done"